version: "3.9"

services:

  steedos:
    image: steedos/steedos-community:2.4
    ports:
      - "5000:5000"
    env_file:
      - .env.local
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongodb:27017/steedos
      - MONGO_OPLOG_URL=mongodb://mongodb:27017/local
      - TRANSPORTER=nats://nats:4222
      - CACHER=redis://redis:6379
      - STEEDOS_IDENTITY_OIDC_ENABLED=true
      - STEEDOS_IDENTITY_OIDC_CONFIG_URL=https://id.steedos.cn/realms/master/.well-known/openid-configuration
      - STEEDOS_IDENTITY_OIDC_CLIENT_ID=steedos-oidc-public
      - STEEDOS_IDENTITY_OIDC_CLIENT_SECRET=none
      - STEEDOS_IDENTITY_OIDC_NAME=Steedos ID
      - STEEDOS_INITIAL_PACKAGES=@steedos-labs/project-ee,@steedos-labs/demo-ee,@steedos-labs/flows
    volumes:
      - "steedos-installed-packages:/app/.steedos"
      - "steedos-data:/app/storage"
      - "./steedos.config.js:/app/steedos.config.js"
      # 使用 docker 启动项目中的软件包
      # - "./steedos-packages:/app/steedos-packages"
    depends_on:
      mongodb:
        condition: service_healthy
        
  redis:
    image: redis:6.2
    command: "redis-server --save \"\" --appendonly no --loglevel warning"
    ports:
      - "6379:6379"
  
  mongodb:
    image: mongo:4.4
    ports:
      - 27017:27017
    command: "--bind_ip_all --replSet steedos --logpath /var/log/mongodb/mongod.log"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - 'steedos-mongo-data:/data/db'

  mongodb-init:
    image: mongo:4.4
    restart: "no"
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      mongo --host mongodb:27017 --eval "rs.initiate({ _id: 'steedos', members: [{_id: 0, host: 'mongodb:27017'}]})"

  # Micro Service Transporter
  nats:
    image: nats:2.9
    ports:
      - "4222:4222"
      # - "8222:8222" # monitor port

volumes:
  steedos-mongo-data:
    driver: local
  steedos-installed-packages:
    driver: local
  steedos-data:
    driver: local
