version: "3.9"

services:

  redis:
    image: ecr.aws.steedos.cn/dockerhub/bitnami/redis:6.2
    command: "redis-server --save \"\" --appendonly no --loglevel warning"
    ports:
      - "6379:6379"
  
  mongodb:
    image: ecr.aws.steedos.cn/dockerhub/bitnami/mongodb:4.4
    ports:
      - 27017:27017
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb
      - MONGODB_REPLICA_SET_NAME=steedos
      - MONGODB_ENABLE_JOURNAL=true
      - MONGODB_ADVERTISED_HOSTNAME=mongodb
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - 'steedos-mongo-data:/bitnami'

volumes:
  steedos-mongo-data:
    driver: local